### ISSUE TITLE
Discrepancy in Values between "GhgEmissions" and "pcf" in Example 31 - Seeking Clarification

### ISSUE THREAD

**Issue by ccumaya** [wbcsd/data-exchange-protocol#13]
In the document "Technical Specifications for PCF Data Exchange (Version 2.0.1-20230720)," available at [https://wbcsd.github.io/data-exchange-protocol/v2/](https://wbcsd.github.io/data-exchange-protocol/v2/), there is a section labeled "6.10.1. Example Action ListFootprints request and response," specifically within Example 31.

I'm curious about the numerical values presented in this example, particularly the contrast between the value for "GhgEmissions" and that of "pcf." While "GhgEmissions" is assigned a value, "pcf" appears to be set at 0.

For instance:
"pCfExcludingBiogenic": "0.0",
"fossilGhgEmissions": "0.123",
"landManagementGhgEmissions": "0.01",

Could you kindly explain the rationale behind this discrepancy? Your insights would be greatly appreciated.

**Comment by raimundo-henriques** [comment]
Dear ccumaya,
    
On behalf of the PACT team, I would like to thank you for your question and apologize for the delay. Since GitHub issues are not a part of our workflow, we did not notice that you were still waiting for a reply.
    
All examples in the Technical Specifications were meant solely for syntactical purposes. They are not examples of actual product footprints, but rather examples of the Data Model.

We are aware that our examples could be more realistic and are working on improving them. As a first step in that direction, we will be fixing the specific issue you have raises, so that there is no such discrepancy, but changing the value of `pCfExcludingBiogenic` to `0.123`. (See #57)

We sincerely thank you for having brought this to our attention. 
    
Thank you,
Best regards,
