### ISSUE TITLE
Broken Link in References for Pathfinder Framework documentation link

### ISSUE THREAD

**Issue by JohnVonNeumann** [wbcsd/data-exchange-protocol#59]
https://wbcsd.github.io/data-exchange-protocol/v2/#normative

> [PATHFINDER-FRAMEWORK]
> [Pathfinder Framework: Guidance for the Accounting and Exchange of Product Life Cycle Emissions (Version 2.0)](https://www.carbon-transparency.com/media/srhhloun/pathfinder-framework.pdf). LS. URL: https://www.carbon-transparency.com/media/srhhloun/pathfinder-framework.pdf

Clicking the link just sends you to:

https://www.carbon-transparency.com/

**Comment by zeitgeist** [comment]
Hello Louis,Thank you for reporting this. It is due to the ongoing relaunch of the website. We will make a proposal to fix this.Am 02.04.2024 um 07:05 schrieb Louis W ***@***.***>:﻿
https://wbcsd.github.io/data-exchange-protocol/v2/#normative

[PATHFINDER-FRAMEWORK]
Pathfinder Framework: Guidance for the Accounting and Exchange of Product Life Cycle Emissions (Version 2.0). LS. URL: https://www.carbon-transparency.com/media/srhhloun/pathfinder-framework.pdf

Clicking the link just sends you to:
https://www.carbon-transparency.com/

**Comment by zeitgeist** [comment]
A brief update: we talked about this today. @bhadley is aligning internally to see where to put the Pathfinder Framewor such that we have (finally) stable links to it. Meanwhile, if you need, you can find it here: https://www.wbcsd.org/contentwbc/download/15625/226889/1
